server:
  port: 8888

logging:
  level:
    org.springframework.cloud.config: DEBUG

spring:
  application:
    name: config-service

  cloud:
    config:
      server:
        git:
          uri: https://github.com/KangHyeon3315/MicroBlogConfig.git

    consul:
      host: localhost
      port: 8500

---
spring:
  config:
    activate:
      on-profile: docker

  cloud:
    consul:
      host: consul

    config:
      server:
        git:
          uri: https://github.com/KangHyeon3315/MicroBlogConfig.git