logging:
  level:
    root: INFO
#    org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator: INFO
#    org.springframework.cloud.gateway: TRACE

server:
  port: 443

  ssl:
    key-store: /Users/kh/Project/MicroBlog/microservices/gateway-service/keystore.p12
    key-store-password: mypassword
    key-store-type: PKCS12
    key-alias: microblog

spring:
  application:
    name: gateway-service
  cloud:
    consul:
      host: localhost
      port: 8500

    gateway:
      routes:
        - id: composite
          uri:
            lb://composite-service

          predicates:
            - Path=/composite/**

---
spring:
  config:
    activate:
      on-profile: docker

  cloud:
    consul:
      host: consul

server:
  port: 443

  ssl:
    key-store: /keystore.p12
