version: "2.1"

services:
  consul:
    image: consul
    ports:
      - "8500:8500"

  config:
    build: microservices/config-service
    mem_limit: 350m
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - "8888:8888"
    healthcheck:
      test: [ "CMD-SHELL", "curl --fail http://config:8888/actuator || exit 1" ]
      interval: 1s
      timeout: 1s
      retries: 10


  gateway:
    build: microservices/gateway-service
    mem_limit: 350m
    ports:
#      - "8080:8080"
      - "443:443"
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  post:
    build: microservices/post-service
    mem_limit: 350m
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  comment:
    build: microservices/comment-service
    mem_limit: 350m
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  user:
    build: microservices/user-service
    mem_limit: 350m
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  composite:
    build: microservices/composite
    mem_limit: 350m
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    restart: on-failure
    depends_on:
      config:
        condition: service_healthy
