server:
  port: 8000
  error:
    include-message: always

logging:
  level:
    root: info
    com:
      microblog: debug

spring:
  application:
    name: composite-service

  config:
    import: "optional:configserver:"


  cloud:
    consul:
      host: localhost
      port: 8500
