
server:
  port: 8001
  error:
    include-message: always

logging:
  level:
    root: info
    com:
      microblog: debug

---
spring:
  config:
    activate:
      on-profile: docker

server:
  port: 8080